files:
- generatedChecksum: E4894B6355AF41AED546E4C6C20005C1
  logicalPath: FreeRTOS/Source
  name: FreeRTOS_tasks.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: E4894B6355AF41AED546E4C6C20005C1
- generatedChecksum: null
  logicalPath: ''
  name: app_task1.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_task2.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_task3.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 64D0F9C57F1452BD074A574237B811D7
  logicalPath: config/pic32mx_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64D0F9C57F1452BD074A574237B811D7
- generatedChecksum: 4490B523D4D89767AF3FE31B825F7F6D
  logicalPath: FreeRTOS/Source
  name: croutine.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4490B523D4D89767AF3FE31B825F7F6D
- generatedChecksum: 0E0E8AECB67046FEA847B359ACE7A1F6
  logicalPath: FreeRTOS/Source
  name: event_groups.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E0E8AECB67046FEA847B359ACE7A1F6
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mx_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: CF89BE92AE72229779903C2E9A760455
  logicalPath: config/pic32mx_sk
  name: freertos_hooks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CF89BE92AE72229779903C2E9A760455
- generatedChecksum: 31CEE4650E24C72160696DF93B55B48D
  logicalPath: FreeRTOS/Source/portable/MemMang
  name: heap_1.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MemMang
  security: NON_SECURE
  type: SOURCE
  userChecksum: 31CEE4650E24C72160696DF93B55B48D
- generatedChecksum: 6A3996C869C94BE5FBCB2F52B538B9B9
  logicalPath: config/pic32mx_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6A3996C869C94BE5FBCB2F52B538B9B9
- generatedChecksum: 16ACFEFEBC368CDC621C811C1CECC2D0
  logicalPath: config/pic32mx_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16ACFEFEBC368CDC621C811C1CECC2D0
- generatedChecksum: 693AEEDF3C1FF2CE5CF729C79598B97B
  logicalPath: config/pic32mx_sk
  name: interrupts_a.S
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 693AEEDF3C1FF2CE5CF729C79598B97B
- generatedChecksum: 47F98BAFD5D2A077AB529D10DB870AFF
  logicalPath: FreeRTOS/Source
  name: list.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47F98BAFD5D2A077AB529D10DB870AFF
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
  logicalPath: config/pic32mx_sk/osal
  name: osal_freertos.c
  physicalPath: osal
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
- generatedChecksum: 6902DD0021DA94F42DE165233780733C
  logicalPath: config/pic32mx_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6902DD0021DA94F42DE165233780733C
- generatedChecksum: B9075C50D6E5312528847AA1098C60AD
  logicalPath: config/pic32mx_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B9075C50D6E5312528847AA1098C60AD
- generatedChecksum: 746C5D1A8EA389A9153D9BF7DC357EC5
  logicalPath: config/pic32mx_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 746C5D1A8EA389A9153D9BF7DC357EC5
- generatedChecksum: 71A55E6FB476D5BC63BAC48D4B11CF6C
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MX
  name: port.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71A55E6FB476D5BC63BAC48D4B11CF6C
- generatedChecksum: 2428B87E7314744BFC401D825171BEA8
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MX
  name: port_asm.S
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2428B87E7314744BFC401D825171BEA8
- generatedChecksum: 13259EE43A731BF0F46EA946229027BF
  logicalPath: FreeRTOS/Source
  name: queue.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13259EE43A731BF0F46EA946229027BF
- generatedChecksum: A9BDA97498BEA85049883F48FB1094A0
  logicalPath: FreeRTOS/Source
  name: stream_buffer.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: A9BDA97498BEA85049883F48FB1094A0
- generatedChecksum: 1EA354F619D88CE9E45777B37794818B
  logicalPath: config/pic32mx_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1EA354F619D88CE9E45777B37794818B
- generatedChecksum: 2811D7C532CEFF995F8697FCED6A1C34
  logicalPath: FreeRTOS/Source
  name: timers.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2811D7C532CEFF995F8697FCED6A1C34
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mx_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 5E06C8C3B681B9398724569B7DC5AFB8
  logicalPath: FreeRTOS/Source/include
  name: FreeRTOS.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5E06C8C3B681B9398724569B7DC5AFB8
- generatedChecksum: 4ADF4772CBFD1F3A435BCD9746998F0E
  logicalPath: config/pic32mx_sk
  name: FreeRTOSConfig.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4ADF4772CBFD1F3A435BCD9746998F0E
- generatedChecksum: 3F453FC192959EEDBAC9FE16D2E50ED7
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MX
  name: ISR_Support.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX
  security: NON_SECURE
  type: HEADER
  userChecksum: 3F453FC192959EEDBAC9FE16D2E50ED7
- generatedChecksum: null
  logicalPath: ''
  name: app_task1.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_task2.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_task3.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: FD4B83330ACFE1EA60FE03AB81871D8E
  logicalPath: config/pic32mx_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: FD4B83330ACFE1EA60FE03AB81871D8E
- generatedChecksum: 7A852268CAA1F0FBB9E75D327532882A
  logicalPath: config/pic32mx_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A852268CAA1F0FBB9E75D327532882A
- generatedChecksum: 4B11D1A616E95BDD37123685C8434FCF
  logicalPath: FreeRTOS/Source/include
  name: croutine.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 4B11D1A616E95BDD37123685C8434FCF
- generatedChecksum: 921EB20C1615481E98FE8A0014CCD51D
  logicalPath: config/pic32mx_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 921EB20C1615481E98FE8A0014CCD51D
- generatedChecksum: ACB7AD12FD525895ABA47C26F4F9A683
  logicalPath: FreeRTOS/Source/include
  name: deprecated_definitions.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: ACB7AD12FD525895ABA47C26F4F9A683
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: DE52B71A2D274138117243B700F40B11
  logicalPath: FreeRTOS/Source/include
  name: event_groups.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: DE52B71A2D274138117243B700F40B11
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mx_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 58875A2FBF6B0502B6D3B8B5C47F3815
  logicalPath: FreeRTOS/Source/include
  name: list.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 58875A2FBF6B0502B6D3B8B5C47F3815
- generatedChecksum: 5D9D0A05D32C97E2E625020E1795C7F1
  logicalPath: FreeRTOS/Source/include
  name: message_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D9D0A05D32C97E2E625020E1795C7F1
- generatedChecksum: A34AAAD9F0BD596E8FF78D86FD64F869
  logicalPath: FreeRTOS/Source/include
  name: mpu_prototypes.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: A34AAAD9F0BD596E8FF78D86FD64F869
- generatedChecksum: 2ECEDD5114F296955777187904C449C7
  logicalPath: FreeRTOS/Source/include
  name: mpu_wrappers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 2ECEDD5114F296955777187904C449C7
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mx_sk/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 167A43EFF8A31441EBF85AC77958A30B
  logicalPath: config/pic32mx_sk/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 167A43EFF8A31441EBF85AC77958A30B
- generatedChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
  logicalPath: config/pic32mx_sk/osal
  name: osal_freertos.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 08CAE57066302D12E2A32EE07E935AFE
  logicalPath: config/pic32mx_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 08CAE57066302D12E2A32EE07E935AFE
- generatedChecksum: F033C692E7E4F6CB1B4710B9C3AA2316
  logicalPath: config/pic32mx_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: F033C692E7E4F6CB1B4710B9C3AA2316
- generatedChecksum: 8DD6C24BF18C96BDC016D9165DF88FEB
  logicalPath: FreeRTOS/Source/include
  name: portable.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DD6C24BF18C96BDC016D9165DF88FEB
- generatedChecksum: 784F6ECB27E5FFF7F926718D777F0310
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MX
  name: portmacro.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX
  security: NON_SECURE
  type: HEADER
  userChecksum: 784F6ECB27E5FFF7F926718D777F0310
- generatedChecksum: 99A9BD4D90230B49C97BBCEE121C1182
  logicalPath: FreeRTOS/Source/include
  name: projdefs.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 99A9BD4D90230B49C97BBCEE121C1182
- generatedChecksum: F917F55E280C54C23A7541A76AC34225
  logicalPath: FreeRTOS/Source/include
  name: queue.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: F917F55E280C54C23A7541A76AC34225
- generatedChecksum: D7426A4807316E4BB5540458F6F4C68F
  logicalPath: FreeRTOS/Source/include
  name: semphr.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: D7426A4807316E4BB5540458F6F4C68F
- generatedChecksum: 634A3DF879F184ABC5F96107F46AC4B2
  logicalPath: FreeRTOS/Source/include
  name: stack_macros.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 634A3DF879F184ABC5F96107F46AC4B2
- generatedChecksum: A652AC7D4938BE16F535BA3C90C86463
  logicalPath: FreeRTOS/Source/include
  name: stream_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: A652AC7D4938BE16F535BA3C90C86463
- generatedChecksum: 0A58B32A7058D0599EC5F6E3B33D42E6
  logicalPath: FreeRTOS/Source/include
  name: task.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 0A58B32A7058D0599EC5F6E3B33D42E6
- generatedChecksum: 41176F771D22559EFCE82398FCF33668
  logicalPath: FreeRTOS/Source/include
  name: timers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 41176F771D22559EFCE82398FCF33668
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mx_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: null
  logicalPath: config/pic32mx_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 0A6FA09F32457EE88B670700114A44AF
  logicalPath: config/pic32mx_sk
  name: p32MX360F512L.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 0A6FA09F32457EE88B670700114A44AF
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-assembler
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mx_sk;
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-preprocessor
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mx_sk;
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
